DROP TABLE IF EXISTS T_BATCH_RESULT;
CREATE TABLE T_BATCH_RESULT (
  `ID` INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  `CREATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '记录创建时间',
  `BATCH_STATUS` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '跑批状态: 1-跑批结束, 2-正在跑批',
  `ACCOUNT_DATE` date NOT NULL default '0000-00-00' COMMENT '账务日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '跑批开始及结束后记录结果';


DROP TABLE IF EXISTS T_JOB;
CREATE TABLE `T_JOB` (
  `ID` bigint(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '任务ID',
  `REMAINDER` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务分片 Hash 余数',
  `DIVISOR` int(11) UNSIGNED NOT NULL DEFAULT '1' COMMENT '任务分片 Hash 除数',
  `JOB_STATUS` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务状态:1-INIT, 2-PROCESSING, 3-FAIL, 4-DONE',
  `JOB_TYPE` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务类型:1-LOAN,2-CREDIT,3-PRE(任务清理,任务分配,日切,全局唯一任务)',
  `RETRY_TIME` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务失败重试次数',
  `DATABASE_ID` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分库名字(后缀)',
  `TABLE_ID` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分表名字(后缀)',
  `JOB_UUID` varchar(64) NOT NULL DEFAULT '' COMMENT '任务处理机唯一ID',
  `STATUS` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '记录状态:0-正常, 1-不可用',
  `ACCOUNT_DATE` date NOT NULL default '0000-00-00' COMMENT '账务日期',
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  `START_TIME` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '任务开始时间',
  `END_TIME` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '任务结束时间',
  `CREATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '记录创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'Job 控制表';

DROP TABLE IF EXISTS H_JOB;
CREATE TABLE `H_JOB` (
  `ID` bigint(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '任务ID',
  `REMAINDER` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务分片 Hash 余数',
  `DIVISOR` int(11) UNSIGNED NOT NULL DEFAULT '1' COMMENT '任务分片 Hash 除数',
  `JOB_STATUS` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务状态:1-INIT, 2-PROCESSING, 3-FAIL, 4-DONE',
  `JOB_TYPE` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务类型:1-LOAN,2-CREDIT,3-PRE(任务清理,任务分配,日切,全局唯一任务)',
  `RETRY_TIME` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '任务失败重试次数',
  `DATABASE_ID` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分库名字(后缀)',
  `TABLE_ID` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分表名字(后缀)',
  `JOB_UUID` varchar(64) NOT NULL DEFAULT '' COMMENT '任务处理机唯一ID',
  `STATUS` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '记录状态:0-正常, 1-不可用',
  `ACCOUNT_DATE` date NOT NULL default '0000-00-00' COMMENT '账务日期',
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  `START_TIME` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '任务开始时间',
  `END_TIME` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '任务结束时间',
  `CREATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '记录创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Job 历史表';

DROP TABLE T_FAIL_RECORD;
CREATE TABLE `T_FAIL_RECORD` (
  `ID` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT '自增主键',
  `FAILURE_ID` bigint(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败类型对应的 ID, 比如客户失败则记录失败客户ID',
  `FAILURE_TYPE` int(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败类型',
  `JOB_ID` bigint(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '来自 T_JOB 表的主键',
  `JOB_UUID` varchar(64) NOT NULL DEFAULT '' COMMENT 'JOB 的 UUID',
  `ACCOUNT_DATE` date NOT NULL DEFAULT '0000-00-00' COMMENT '账务日期',
  `CREATED` timestamp NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '记录创建时间',
  `MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  `STATUS` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '失败状态',
  KEY `id_type` (`FAILURE_ID`,`FAILURE_TYPE`),
  KEY `jobid_date` (`JOB_ID`,`ACCOUNT_DATE`),
  KEY `account_date` (`ACCOUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '失败记录表';