
--DROP SCHEMA IF EXISTS FCORE_PART_0;
--CREATE SCHEMA FCORE_PART_0;
SET SCHEMA FCORE_PART_0;

DROP TABLE IF EXISTS T_CUSTOMER_ACCOUNT_0_0;
CREATE TABLE T_CUSTOMER_ACCOUNT_0_0 (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
  ACCOUNT_TYPE INT NOT NULL COMMENT '账号类型',
  ACCOUNT_AGING INT NOT NULL COMMENT '账号账龄',
  CUSTOMER_ACCOUNT_STATUS INT NOT NULL COMMENT '账号状态',
  DEBIT_STATUS INT NOT NULL COMMENT '借贷状态',
  PRINCIPAL BIGINT DEFAULT NULL COMMENT '本金余额',
  PRINCIPAL_USABLE BIGINT DEFAULT NULL COMMENT '可用本金余额',
  PRINCIPAL_FREEZE BIGINT DEFAULT NULL COMMENT '冻结本金金额',
  PRINCIPAL_TRANSIT BIGINT DEFAULT NULL COMMENT '在途本金余额',
  INTEREST BIGINT DEFAULT NULL COMMENT '利息余额',
  INTEREST_USABLE BIGINT DEFAULT NULL COMMENT '可用利息余额',
  INTEREST_FREEZE BIGINT DEFAULT NULL COMMENT '冻结利息金额',
  INTEREST_TRANSIT BIGINT DEFAULT NULL COMMENT '在途利息余额',
  CHARGES BIGINT DEFAULT NULL COMMENT '费用余额',
  CHARGES_USABLE BIGINT DEFAULT NULL COMMENT '可用费用余额',
  CHARGES_FREEZE BIGINT DEFAULT NULL COMMENT '冻结费用金额',
  CHARGES_TRANSIT BIGINT DEFAULT NULL COMMENT '在途费用余额',
  PENALTY BIGINT DEFAULT NULL COMMENT '罚息余额',
  PENALTY_USABLE BIGINT DEFAULT NULL COMMENT '可用罚息余额',
  PENALTY_FREEZE BIGINT DEFAULT NULL COMMENT '冻结罚息金额',
  PENALTY_TRANSIT BIGINT DEFAULT NULL COMMENT '在途罚息余额',
  OVERDUE BIGINT DEFAULT NULL COMMENT '滞纳金余额',
  OVERDUE_USABLE BIGINT DEFAULT NULL COMMENT '可用滞纳金余额',
  OVERDUE_FREEZE BIGINT DEFAULT NULL COMMENT '冻结滞纳金金额',
  OVERDUE_TRANSIT BIGINT DEFAULT NULL COMMENT '在途滞纳金余额',
  VIOLATE BIGINT DEFAULT NULL COMMENT '违约金余额',
  VIOLATE_USABLE BIGINT DEFAULT NULL COMMENT '可用违约金余额',
  VIOLATE_FREEZE BIGINT DEFAULT NULL COMMENT '冻结违约金金额',
  VIOLATE_TRANSIT BIGINT DEFAULT NULL COMMENT '在途违约金余额',
  ID_GENERATE_DATE DATE NOT NULL COMMENT '客户ID生成时间',
  DELETE_FLAG INT DEFAULT NULL COMMENT '记录物理状态',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2001-01-01 00:00:00' COMMENT '创建时间'
);
CREATE UNIQUE INDEX IDX_CUSTOMER_ACCOUNT_CUSTOMER_ID ON T_CUSTOMER_ACCOUNT_0_0(CUSTOMER_ID);
CREATE UNIQUE INDEX IDX_CUSTOMER_ACCOUNT_ACCOUNT_ID ON T_CUSTOMER_ACCOUNT_0_0(ACCOUNT_ID);


DROP TABLE IF EXISTS T_CUSTOMER_INFO_0_0;
CREATE TABLE T_CUSTOMER_INFO_0_0 (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  CERTIFICATE_TYPE INT NOT NULL COMMENT '证件类型',
  CERTIFICATE_ID VARCHAR NOT NULL COMMENT '证件号码',
  TELEPHONE_NO VARCHAR DEFAULT NULL COMMENT '电话号码',
  CUSTOMER_STATUS INT DEFAULT NULL COMMENT '客户状态',
  DEBIT_STATUS INT NOT NULL COMMENT '借贷状态',
  CUSTOMER_GRADE INT DEFAULT NULL COMMENT '客户等级',
  CUSTOMER_NAME VARCHAR NOT NULL COMMENT '客户姓名',
  ID_GENERATE_DATE DATE NOT NULL COMMENT '客户ID生成日期',
  DELETE_FLAG INT NOT NULL COMMENT '逻辑删除标记',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2001-01-01 00:00:00' COMMENT '创建时间'
);
CREATE UNIQUE INDEX IDX_CUSTOMER_INFO_CUSTOMER_ID ON T_CUSTOMER_INFO_0_0(CUSTOMER_ID);

DROP TABLE T_CUSTOMER_SIGN_CONTRACT_0_0;
CREATE TABLE T_CUSTOMER_SIGN_CONTRACT_0_0 (
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2001-01-01 00:00:00' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT DEFAULT NULL COMMENT '账号ID',
  ACCOUNT_TYPE INT NOT NULL COMMENT '账号类型',
  PRODUCT_ID BIGINT DEFAULT NULL COMMENT '产品ID',
  PRODUCT_NO BIGINT DEFAULT NULL COMMENT '产品序号',
  CONTRACT_ID BIGINT NOT NULL COMMENT '签约ID',
  M_INTEREST INT NOT NULL COMMENT '定价因子：利息',
  M_CHARGES INT NOT NULL COMMENT '定价因子：费用',
  M_PENALTY INT NOT NULL COMMENT '定价因子：罚息',
  M_OVERDUE INT NOT NULL COMMENT '定价因子：逾期费',
  M_VIOLATE INT NOT NULL COMMENT '定价因子：违约金',
  CONTRACT_STATUS INT NOT NULL COMMENT '签约状态',
  BILL_DAY_RULE INT NOT NULL COMMENT '账单日规则',
  BILL_DAY INT DEFAULT NULL COMMENT '账单日',
  REPAY_DAY_RULE INT NOT NULL COMMENT '还款日规则',
  REPAY_DAY VARCHAR DEFAULT NULL COMMENT '还款日',
  GRACE_DAY INT DEFAULT NULL COMMENT '宽限期',
  INTEREST_START_TYPE INT DEFAULT NULL COMMENT '起息日类型',
  FINANCING_SOURCE INT DEFAULT NULL COMMENT '资金机构',
  PRIMARY KEY(ID)
);
CREATE UNIQUE INDEX IDX_SIGN_CONTRACT_ID ON T_CUSTOMER_SIGN_CONTRACT_0_0(CONTRACT_ID);
CREATE INDEX IDX_SIGN_CUSTOMER_ID ON T_CUSTOMER_SIGN_CONTRACT_0_0(CUSTOMER_ID);
CREATE INDEX IDX_SIGN_ACCOUNT_ID ON T_CUSTOMER_SIGN_CONTRACT_0_0(ACCOUNT_ID);
--INSERT INTO `FCORE_PART_0`.`t_customer_sign_contract_0_0` (`MODIFIED`, `CREATED`, `ID`, `CUSTOMER_ID`, `ACCOUNT_ID`, `ACCOUNT_TYPE`, `PRODUCT_ID`, `PRODUCT_NO`, `CONTRACT_ID`, `M_INTEREST`, `M_CHARGES`, `M_PENALTY`, `M_OVERDUE`, `CONTRACT_STATUS`, `BILL_DAY_RULE`, `BILL_DAY`, `REPAY_DAY_RULE`, `REPAY_DAY`, `GRACE_DAY`, `INTEREST_START_TYPE`, ) VALUES ('2016-05-12 16:00:26', '2016-05-12 16:00:26', '368095', '136261232', '17572191', '1', '73426782', '56119446', '13820739', '10000', '0', '10000',  '10000',  '1', '1', '2', '1', '3,15,22,25', '12', '2');

DROP TABLE IF EXISTS T_INSTALLMENT_SCHEDULE_0_0;
CREATE TABLE T_INSTALLMENT_SCHEDULE_0_0 (
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2001-01-01 00:00:00' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  LOAN_ID BIGINT NOT NULL COMMENT '借据号',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
  PRODUCT_ID BIGINT NOT NULL COMMENT '产品ID',
  PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
  CONTRACT_ID BIGINT NOT NULL COMMENT '签约ID',
  INSTALLMENT_MADE_NO INT NOT NULL COMMENT '借据被分期序号',
  LOAN_SCHEDULE_NO INT NOT NULL COMMENT '借据期序号',
  ACCOUNT_DATE DATE NOT NULL COMMENT '账务日期',
  TRANSACTION_DATE DATE NOT NULL COMMENT '交易日期',
  DUE_DATE DATE NOT NULL COMMENT '到期日',
  INTEREST_START_DATE DATE NOT NULL ,
  GRACE_DATE DATE NOT NULL COMMENT '宽限日',
  STATUS INT NOT NULL COMMENT '还款计划状态',
  TRANSACTION_ID BIGINT NOT NULL COMMENT '上一次交易流水ID',
  PRINCIPAL BIGINT NOT NULL COMMENT '本金总额',
  PRINCIPAL_REPAY BIGINT NOT NULL COMMENT '本金已还金额',
  PRINCIPAL_UNPAID BIGINT NOT NULL COMMENT '本金未还',
  INTEREST BIGINT NOT NULL COMMENT '利息总额',
  INTEREST_REPAY BIGINT NOT NULL COMMENT '利息已还金额',
  INTEREST_UNPAID BIGINT NOT NULL COMMENT '利息未还',
  CHARGES BIGINT NOT NULL COMMENT '费用总额',
  CHARGES_REPAY BIGINT NOT NULL COMMENT '费用已还金额',
  CHARGES_UNPAID BIGINT NOT NULL COMMENT '费用未还',
  PENALTY BIGINT NOT NULL COMMENT '罚息总额',
  PENALTY_REPAY BIGINT NOT NULL COMMENT '罚息已还金额',
  PENALTY_UNPAID BIGINT NOT NULL COMMENT '罚息未还',
  OVERDUE BIGINT NOT NULL COMMENT '逾期费总额',
  OVERDUE_REPAY BIGINT NOT NULL COMMENT '逾期费已还金额',
  OVERDUE_UNPAID BIGINT NOT NULL COMMENT '逾期费未还',
  VIOLATE BIGINT NOT NULL COMMENT '违约金总额',
  VIOLATE_REPAY BIGINT NOT NULL COMMENT '违约金已还金额',
  VIOLATE_UNPAID BIGINT NOT NULL COMMENT '违约金未还',
  MANAGEMENT BIGINT NOT NULL COMMENT '账户管理费总金额',
  MANAGEMENT_REPAY BIGINT NOT NULL COMMENT '账户管理费已还金额',
  MANAGEMENT_UNPAID BIGINT NOT NULL COMMENT '账户管理费未还',
  SERVICE BIGINT NOT NULL COMMENT '服务费总金额',
  SERVICE_REPAY BIGINT NOT NULL COMMENT '服务费已还金额',
  SERVICE_UNPAID BIGINT NOT NULL COMMENT '服务费未还',
  DISCOUNT BIGINT DEFAULT NULL COMMENT '当期贴息',
  ACCOUNTING_PRINCIPAL BIGINT DEFAULT NULL COMMENT '会计本金',
  SECURITY_STATUS INT DEFAULT NULL COMMENT '证券化状态',
  SECURITY_SALE_DATE DATE DEFAULT NULL COMMENT '证券化销售日期',
  SECURITY_INSTITUTION_ID BIGINT DEFAULT NULL COMMENT '证券化销售机构ID',
  VERSION INT COMMENT '版本',
  PRIMARY KEY (`ID`)
);
-- CREATE INDEX IDX_INSTALLMENT_STATUS ON T_INSTALLMENT_SCHEDULE_0_0(STATUS);
-- CREATE INDEX IDX_INSTALLMENT_CUSTOMER ON T_INSTALLMENT_SCHEDULE_0_0(CUSTOMER_ID);
-- CREATE INDEX IDX_INSTALLMENT_LOAN ON T_INSTALLMENT_SCHEDULE_0_0(LOAN_ID);
-- CREATE INDEX IDX_INSTALLMENT_ACCOUNT ON T_INSTALLMENT_SCHEDULE_0_0(ACCOUNT_ID);
-- CREATE INDEX IDX_INSTALLMENT_GRACE_DATE ON T_INSTALLMENT_SCHEDULE_0_0(GRACE_DATE);

DROP TABLE IF EXISTS T_LOAN_0_0;
CREATE TABLE T_LOAN_0_0 (
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2001-01-01 00:00:00' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  LOAN_ID BIGINT NOT NULL COMMENT '借据号',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
  PRODUCT_ID BIGINT NOT NULL COMMENT '产品ID',
  PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
  CONTRACT_ID BIGINT NOT NULL COMMENT '签约ID',
  INSTALLMENT_COUNT INT NOT NULL COMMENT '分期期数',
  LOAN_AGE INT NOT NULL COMMENT '借据账龄',
  ACCOUNT_DATE DATE NOT NULL COMMENT '账务日期',
  TRANSACTION_ID BIGINT NOT NULL COMMENT '上一次交易流水ID',
  INSTALLMENT_MADE_NO INT NOT NULL COMMENT '借据当前使用的被分期序号',
  INSTALLMENT_MADE_TIMES INT DEFAULT NULL COMMENT '借据被分期的总次数',
  INTEREST_START_DATE DATE NOT NULL COMMENT '起息日期',
  LOAN_CHANNEL BIGINT DEFAULT NULL COMMENT '放款渠道',
  FINANCING_SOURCE BIGINT NOT NULL COMMENT '资金机构',
  REPAY_DAY INT NOT NULL COMMENT '还款日',
  GRACE_DAY INT NOT NULL COMMENT '宽限期',
  PRINCIPAL BIGINT NOT NULL COMMENT '本金总额',
  PRINCIPAL_REPAY BIGINT NOT NULL COMMENT '本金已还金额',
  PRINCIPAL_UNPAID BIGINT NOT NULL COMMENT '本金未还',
  INTEREST BIGINT NOT NULL COMMENT '利息总额',
  INTEREST_REPAY BIGINT NOT NULL COMMENT '利息已还金额',
  INTEREST_UNPAID BIGINT NOT NULL COMMENT '利息未还',
  INTEREST_MULTIPLIER INT NOT NULL COMMENT '利息因子',
  CHARGES BIGINT NOT NULL COMMENT '费用总额',
  CHARGES_REPAY BIGINT NOT NULL COMMENT '费用已还金额',
  CHARGES_UNPAID BIGINT NOT NULL COMMENT '费用未还',
  CHARGES_MULTIPLIER INT NOT NULL COMMENT '费用因子',
  PENALTY BIGINT NOT NULL COMMENT '罚息总额',
  PENALTY_REPAY BIGINT NOT NULL COMMENT '罚息已还金额',
  PENALTY_UNPAID BIGINT NOT NULL COMMENT '罚息未还',
  PENALTY_MULTIPLIER INT NOT NULL COMMENT '罚息因子',
  OVERDUE BIGINT NOT NULL COMMENT '滞纳金总额',
  OVERDUE_REPAY BIGINT NOT NULL COMMENT '滞纳金已还金额',
  OVERDUE_UNPAID BIGINT NOT NULL COMMENT '滞纳金未还',
  OVERDUE_MULTIPLIER INT NOT NULL COMMENT '滞纳金因子',
  VIOLATE BIGINT NOT NULL COMMENT '违约金总额',
  VIOLATE_REPAY BIGINT NOT NULL COMMENT '违约金已还金额',
  VIOLATE_UNPAID BIGINT NOT NULL COMMENT '违约金未还',
  VIOLATE_MULTIPLIER INT NOT NULL COMMENT '违约金因子',
  MANAGEMENT BIGINT NOT NULL COMMENT '账户管理费总金额',
  MANAGEMENT_REPAY BIGINT NOT NULL COMMENT '账户管理费已还金额',
  MANAGEMENT_UNPAID BIGINT NOT NULL COMMENT '账户管理费未还',
  MANAGEMENT_MULTIPLIER BIGINT NOT NULL COMMENT '账户管理费因子',
  SERVICE BIGINT NOT NULL COMMENT '服务费总金额',
  SERVICE_REPAY BIGINT NOT NULL COMMENT '服务费已还金额',
  SERVICE_UNPAID BIGINT NOT NULL COMMENT '服务费未还',
  SERVICE_MULTIPLIER INT NOT NULL COMMENT '服务费因子',
  DISCOUNT BIGINT NOT NULL COMMENT '贴息总额',
  IS_DISCOUNT_REFUND INT NOT NULL COMMENT '退款时是否退贴息',
  DISCOUNT_REFUND BIGINT DEFAULT NULL COMMENT '退款时退贴息的金额',
  LOAN_STATUS INT NOT NULL COMMENT '贷款状态',
  IRR BIGINT NOT NULL COMMENT '内部收益率',
  WRITE_OFF_ID INT NOT NULL COMMENT '冲销方式',
  SECURITY_STATUS INT DEFAULT NULL COMMENT '证券化状态',
  SECURITY_SALE_DATE DATE DEFAULT NULL COMMENT '证券化销售日期',
  SECURITY_INSTITUTION_ID BIGINT DEFAULT NULL COMMENT '证券化销售机构id',
  NOTES VARCHAR DEFAULT NULL COMMENT '摘要说明',
  APPLY_DATE DATE NOT NULL COMMENT '申请日期',
  CONFIRM_DATE DATE DEFAULT NULL COMMENT '确认日期',
  CAN_FUTURE_REPAY INT DEFAULT NULL COMMENT '未来期是否可以正常还',
  VIOLATE_PREPAY_MULTIPLIER BIGINT NOT NULL ,
  VIOLATE_REFUND_MULTIPLIER BIGINT NOT NULL ,
  CLEAR_DATE DATE NOT NULL,
  VERSION INT NOT NULL COMMENT '版本',
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS T_BILL_0_0;
CREATE TABLE T_BILL_0_0
(
  MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  BILL_ID BIGINT COMMENT '账单ID',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
  PRODUCT_ID BIGINT NOT NULL COMMENT '产品ID',
  PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
  ACCOUNT_DATE DATE NOT NULL COMMENT '帐务日期',
  BILL_DATE DATE NOT NULL COMMENT '账单日',
  DUE_DATE DATE NOT NULL COMMENT '还款日',
  GRACE_DATE DATE NOT NULL COMMENT '宽限日',
  BILL_REPAY BIGINT NOT NULL COMMENT '账单金额汇总',
  MIN_REPAY BIGINT NOT NULL COMMENT '最小还款额',
  CURRENT_REPAID BIGINT NOT NULL COMMENT '本期已还',
  REMAINDER BIGINT NOT NULL COMMENT '账单余额',
  REPAID_DELTA BIGINT NOT NULL COMMENT '本期当日还款累加',
  CURRENT_CONSUME BIGINT NOT NULL COMMENT '当期消费金额',
  CURRENT_CONSUME_REPAID BIGINT NOT NULL COMMENT '当期消费金额已还',
  H_CONSUME BIGINT NOT NULL COMMENT '往期消费金额',
  H_CONSUME_REPAID BIGINT NOT NULL COMMENT '往期消费金额已还',
  CURRENT_INSTALLMENT BIGINT NOT NULL COMMENT '当期摊销本金',
  CURRENT_INSTALLMENT_REPAID BIGINT NOT NULL COMMENT '当期摊销本金已还',
  H_INSTALLMENT BIGINT NOT NULL COMMENT '往期摊销本金',
  H_INSTALLMENT_REPAID BIGINT NOT NULL COMMENT '往期摊销本金已还',
  CURRENT_INTEREST BIGINT NOT NULL COMMENT '当期利息',
  CURRENT_INTEREST_REPAID BIGINT NOT NULL COMMENT '当期利息已还',
  H_INTEREST BIGINT NOT NULL COMMENT '往期利息',
  H_INTEREST_REPAID BIGINT NOT NULL COMMENT '往期利息已还',
  CURRENT_VIOLATE BIGINT NOT NULL COMMENT '当期违约金',
  CURRENT_VIOLATE_REPAID BIGINT NOT NULL COMMENT '当期违约金已还',
  H_VIOLATE BIGINT NOT NULL COMMENT '往期违约金',
  H_VIOLATE_REPAID BIGINT NOT NULL COMMENT '往期违约金已还',
  CURRENT_CHARGES BIGINT NOT NULL COMMENT '当期费用',
  CURRENT_CHARGES_REPAID BIGINT NOT NULL COMMENT '当期费用已还',
  H_CHARGES BIGINT NOT NULL COMMENT '往期费用',
  H_CHARGES_REPAID BIGINT NOT NULL COMMENT '往期费用已还',
  BILL_REPAY_STATUS INT NOT NULL COMMENT '账单状态',
  INSTALLMENT_STATUS INT NOT NULL COMMENT '转分期状态',
  WRITE_OFF_ID BIGINT NOT NULL COMMENT '冲销方式ID',
  TRANSACTION_ID BIGINT NOT NULL COMMENT '上一次交易流水ID',
  VERSION INT NOT NULL COMMENT '版本',
  PRIMARY KEY(ID)
);
DROP TABLE IF EXISTS T_CONSUME_0_0;
CREATE TABLE T_CONSUME_0_0
(
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT COMMENT '账号ID',
  PRODUCT_ID BIGINT COMMENT '产品ID',
  PRODUCT_NO BIGINT COMMENT '产品序号',
  TRANSACTION_ID BIGINT NOT NULL COMMENT '交易ID',
  CONSUME_ID BIGINT NOT NULL COMMENT '消费明细ID',
  BILL_ID BIGINT COMMENT '对应账单ID',
  TRANSACTION_DATE DATE NOT NULL COMMENT '交易发起日期',
  TRANSACTION_CONFIRMED_DATE DATE COMMENT '交易确认日期',
  TRANSACTION_CANCELLED_DATE DATE COMMENT '交易取消日期',
  BILL_DATE DATE NOT NULL COMMENT '账单日期',
  REPAY_DATE DATE NOT NULL COMMENT '还款日期',
  CONSUME_AMOUNT BIGINT NOT NULL COMMENT '交易总额',
  CONSUME_STATUS INT NOT NULL COMMENT '消费状态',
  REPAID_AMOUNT BIGINT COMMENT '已还金额',
  BILL_STATUS INT NOT NULL COMMENT '账单状态',
  INSTALLMENT_STATUS INT NOT NULL COMMENT '分期状态',
  INSTALLMENT_BILL_ID BIGINT COMMENT '转分期的分期账单id',
  FLUSH_STATUS int NOT NULL COMMENT '跑批冲销状态',
  NOTES VARCHAR(32) COMMENT '摘要说明',
  CONSUME_TYPE  int NOT NULL COMMENT '消费交易类型',
  OVER_PAID BIGINT COMMENT '溢缴款',
  VERSION INT NOT NULL COMMENT '版本',
  PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS T_CREDIT_INSTALLMENT_0_0;
CREATE TABLE T_CREDIT_INSTALLMENT_0_0
(
  MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  INSTALLMENT_ID BIGINT COMMENT '全局唯一ID',
  INSTALLMENT_TYPE INT COMMENT '分期类型',
  BILL_ID BIGINT COMMENT '账单ID',
  CONSUME_ID BIGINT COMMENT '消费ID',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
  PRODUCT_ID BIGINT COMMENT '产品ID',
  PRODUCT_NO BIGINT COMMENT '产品序号',
  INSTALLMENT_COUNT INT COMMENT '总分期数',
  INSTALLMENT_NO INT COMMENT '分期序号',
  ACCOUNT_DATE DATE NOT NULL COMMENT '帐务日期',
  BILL_DATE DATE NOT NULL COMMENT '账单日',
  DUE_DATE DATE NOT NULL COMMENT '到期还款日',
  PRINCIPAL BIGINT NOT NULL COMMENT '本金总金额',
  PRINCIPAL_REPAID BIGINT NOT NULL COMMENT '本金已还金额',
  PRINCIPAL_UNPAID BIGINT NOT NULL COMMENT '本金未还金额',
  CHARGES BIGINT NOT NULL COMMENT '费用总额',
  CHARGES_REPAID BIGINT NOT NULL COMMENT '费用已还金额',
  CHARGES_UNPAID BIGINT NOT NULL COMMENT '费用未还金额',
  PENALTY BIGINT NOT NULL COMMENT '罚息总额',
  PENALTY_REPAID BIGINT NOT NULL COMMENT '罚息已还金额',
  PENALTY_UNPAID BIGINT NOT NULL COMMENT '罚息未还金额',
  OVERDUE BIGINT NOT NULL COMMENT '逾期费总额',
  OVERDUE_REPAID BIGINT NOT NULL COMMENT '逾期费已还金额',
  OVERDUE_UNPAID BIGINT NOT NULL COMMENT '逾期费未还金额',
  VIOLATE BIGINT COMMENT '违约金总额',
  VIOLATE_REPAID BIGINT NOT NULL COMMENT '违约金已还金额',
  VIOLATE_UNPAID BIGINT COMMENT '违约金未还金额',
  REPAID_STATUS INT NOT NULL COMMENT '还款状态',
  INSTALLMENT_STATUS INT NOT NULL COMMENT '信用支付分期状态',
  BILL_STATUS INT NOT NULL COMMENT '账单状态',
  TRANSACTION_ID BIGINT DEFAULT NULL COMMENT '交易ID',
  GRACE_DATE DATE NOT NULL COMMENT '宽限日',
  VERSION INT NOT NULL COMMENT '版本',
  PRIMARY KEY(ID)
);
CREATE INDEX IDX_LAON_CUSTOMER_ID ON T_LOAN_0_0(CUSTOMER_ID);
CREATE INDEX IDX_LOAN_LOAN ON T_LOAN_0_0(LOAN_ID);
CREATE INDEX IDX_LOAN_ACCOUNT ON T_LOAN_0_0(ACCOUNT_ID);

DROP TABLE IF EXISTS T_BILL_0_0;
CREATE TABLE T_BILL_0_0
(
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
BILL_ID BIGINT COMMENT '账单ID',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
PRODUCT_ID BIGINT NOT NULL COMMENT '产品ID',
PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
ACCOUNT_DATE DATE NOT NULL COMMENT '帐务日期',
BILL_DATE DATE NOT NULL COMMENT '账单日',
DUE_DATE DATE NOT NULL COMMENT '还款日',
GRACE_DATE DATE NOT NULL COMMENT '宽限日',
BILL_REPAY BIGINT NOT NULL COMMENT '账单金额汇总',
MIN_REPAY BIGINT NOT NULL COMMENT '最小还款额',
CURRENT_REPAID BIGINT NOT NULL COMMENT '本期已还',
REMAINDER BIGINT NOT NULL COMMENT '账单余额',
REPAID_DELTA BIGINT NOT NULL COMMENT '本期当日还款累加',
CURRENT_CONSUME BIGINT NOT NULL COMMENT '当期消费金额',
CURRENT_CONSUME_REPAID BIGINT NOT NULL COMMENT '当期消费金额已还',
H_CONSUME BIGINT NOT NULL COMMENT '往期消费金额',
H_CONSUME_REPAID BIGINT NOT NULL COMMENT '往期消费金额已还',
CURRENT_INSTALLMENT BIGINT NOT NULL COMMENT '当期摊销本金',
CURRENT_INSTALLMENT_REPAID BIGINT NOT NULL COMMENT '当期摊销本金已还',
H_INSTALLMENT BIGINT NOT NULL COMMENT '往期摊销本金',
H_INSTALLMENT_REPAID BIGINT NOT NULL COMMENT '往期摊销本金已还',
CURRENT_INTEREST BIGINT NOT NULL COMMENT '当期利息',
CURRENT_INTEREST_REPAID BIGINT NOT NULL COMMENT '当期利息已还',
H_INTEREST BIGINT NOT NULL COMMENT '往期利息',
H_INTEREST_REPAID BIGINT NOT NULL COMMENT '往期利息已还',
CURRENT_VIOLATE BIGINT NOT NULL COMMENT '当期违约金',
CURRENT_VIOLATE_REPAID BIGINT NOT NULL COMMENT '当期违约金已还',
H_VIOLATE BIGINT NOT NULL COMMENT '往期违约金',
H_VIOLATE_REPAID BIGINT NOT NULL COMMENT '往期违约金已还',
CURRENT_CHARGES BIGINT NOT NULL COMMENT '当期费用',
CURRENT_CHARGES_REPAID BIGINT NOT NULL COMMENT '当期费用已还',
H_CHARGES BIGINT NOT NULL COMMENT '往期费用',
H_CHARGES_REPAID BIGINT NOT NULL COMMENT '往期费用已还',
BILL_REPAY_STATUS INT NOT NULL COMMENT '账单状态',
INSTALLMENT_STATUS INT NOT NULL COMMENT '转分期状态',
WRITE_OFF_ID BIGINT NOT NULL COMMENT '冲销方式ID',
TRANSACTION_ID BIGINT NOT NULL COMMENT '上一次交易流水ID',
FINANCING_SOURCE INT DEFAULT NULL COMMENT '资金机构',
VERSION INT NOT NULL COMMENT '版本',
PRIMARY KEY(ID),
INDEX IDX_BILL_CUSTOMER(CUSTOMER_ID),
INDEX IDX_BILL_ACCOUNT(ACCOUNT_ID),
UNIQUE IDX_BILL_BILL(BILL_ID)
);



DROP TABLE IF EXISTS T_FAIL_RECORD;
CREATE TABLE T_FAIL_RECORD (
MODIFIED TIMESTAMP NOT NULL COMMENT '记录修改时间',
CREATED TIMESTAMP NOT NULL COMMENT '记录创建时间',
ID INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
FAILURE_ID BIGINT NOT NULL COMMENT '失败的记录ID',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
ACCOUNT_DATE DATE NOT NULL COMMENT '失败的账务日期',
STATUS INT NOT NULL COMMENT '状态',
PRIMARY KEY(ID)
);

-- 未分库分表的数据库结构
DROP TABLE IF EXISTS DAY_CUT_INFO;
CREATE TABLE DAY_CUT_INFO (
  ID INT NOT NULL AUTO_INCREMENT,
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01',
  ACCOUNT_DATE DATE NOT NULL
);
INSERT INTO `fcore_part_0`.`DAY_CUT_INFO` (`ID`, `MODIFIED`, `CREATED`, `ACCOUNT_DATE`) VALUES ('1', '2016-06-01 02:31:27', '2016-05-31 22:28:12', '2016-07-19');


DROP TABLE IF EXISTS DAY_CUT_INFO_HIST;
CREATE TABLE DAY_CUT_INFO_HIST (
  ID INT  NOT NULL AUTO_INCREMENT,
  DAY_CUT_MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DAY_CUT_CREATED TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01',
  ACCOUNT_DATE DATE NOT NULL
);

DROP TABLE IF EXISTS T_BATCH_RESULT;
CREATE TABLE T_BATCH_RESULT (
  ID INT  NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '记录创建时间',
  BATCH_STATUS INT NOT NULL DEFAULT '0' COMMENT '跑批状态: 1-跑批结束, 2-正在跑批',
  ACCOUNT_DATE DATE NOT NULL DEFAULT '2010-01-01' COMMENT '账务日期'
);
CREATE PRIMARY KEY ON T_BATCH_RESULT(ID);

DROP TABLE IF EXISTS T_JOB;
CREATE TABLE T_JOB (
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '记录创建时间',
  ID INT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  PHASE INT NOT NULL COMMENT '处理阶段',
  PHASE_STATUS INT NOT NULL COMMENT '阶段状态',
  RETRY_TIME INT NOT NULL COMMENT '重试次数',
  CHECK_POINT INT NOT NULL COMMENT '失败时恢复点',
  JOB_TYPE INT NOT NULL COMMENT '任务类型',
  DATABASE_ID VARCHAR NOT NULL COMMENT '分库号',
  TABLE_ID VARCHAR NOT NULL COMMENT '分表号',
  UUID VARCHAR NOT NULL COMMENT '运行该任务的处理机UUID',
  ACCOUNT_DATE DATE NOT NULL COMMENT '账务日期',
  START_TIME TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '任务运行开始时间',
  END_TIME TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '任务运行结束时间'
);
CREATE PRIMARY KEY ON T_JOB(ID);

DROP TABLE IF EXISTS M_PRICING_METHOD;
CREATE TABLE M_PRICING_METHOD (
  STATUS INT NOT NULL COMMENT '状态',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  PRICING_METHOD_ID BIGINT NOT NULL COMMENT '定价方式ID',
  PRICING_METHOD_NAME VARCHAR(150) NOT NULL COMMENT '定价方式名称',
  REPAYMENT_METHOD_ID BIGINT NOT NULL COMMENT '还款方式ID',
  REPAYMENT_NO INT NOT NULL COMMENT '还款期数',
  PRICING_TYPE INT NOT NULL COMMENT '定价类型',
  PRICING_MODE INT NOT NULL COMMENT '定价计算规则',
  FIXED_AMOUNT BIGINT NOT NULL COMMENT '固定收取金额',
  MIN_AMOUNT BIGINT NOT NULL COMMENT '最小收取金额',
  PERCENT_VALUE INT NOT NULL COMMENT '利率',
  PRINCIPAL_MODE INT NOT NULL COMMENT '本金处理方式',
  YMD_FLAG INT NOT NULL COMMENT '年月日标志',
  YEAR_BASE_DAY INT NOT NULL COMMENT '年基准天数',
  MONTH_BASE_DAY INT NOT NULL COMMENT '月基准天数'
);
CREATE PRIMARY KEY ON M_PRICING_METHOD(ID);
CREATE INDEX IDX_PM_ID ON M_PRICING_METHOD(PRICING_METHOD_ID);
CREATE INDEX IDX_PM_REPAYMENT ON M_PRICING_METHOD(REPAYMENT_NO,PRICING_TYPE,REPAYMENT_METHOD_ID);

INSERT INTO `M_PRICING_METHOD` (`STATUS`, `MODIFIED`, `CREATED`, `ID`, `PRICING_METHOD_ID`, `PRICING_METHOD_NAME`, `REPAYMENT_METHOD_ID`, `REPAYMENT_NO`, `PRICING_TYPE`, `PRICING_MODE`, `FIXED_AMOUNT`, `MIN_AMOUNT`, `PERCENT_VALUE`, `PRINCIPAL_MODE`, `YMD_FLAG`, `YEAR_BASE_DAY`, `MONTH_BASE_DAY`) VALUES ('1', '2016-05-22 22:08:48', '2016-05-09 15:01:58', '1', '50001', 'installment', '1', '-1', '2', '1', '0', '1', '1000', '0', '0', '365', '30');
INSERT INTO `M_PRICING_METHOD` (`STATUS`, `MODIFIED`, `CREATED`, `ID`, `PRICING_METHOD_ID`, `PRICING_METHOD_NAME`, `REPAYMENT_METHOD_ID`, `REPAYMENT_NO`, `PRICING_TYPE`, `PRICING_MODE`, `FIXED_AMOUNT`, `MIN_AMOUNT`, `PERCENT_VALUE`, `PRINCIPAL_MODE`, `YMD_FLAG`, `YEAR_BASE_DAY`, `MONTH_BASE_DAY`) VALUES ('1', '2016-05-22 22:08:49', '2016-05-22 22:01:53', '222222', '4', ' ', '1', '-1', '4', '1', '0', '2', '2000', '0', '0', '365', '30');
INSERT INTO `M_PRICING_METHOD` (`STATUS`, `MODIFIED`, `CREATED`, `ID`, `PRICING_METHOD_ID`, `PRICING_METHOD_NAME`, `REPAYMENT_METHOD_ID`, `REPAYMENT_NO`, `PRICING_TYPE`, `PRICING_MODE`, `FIXED_AMOUNT`, `MIN_AMOUNT`, `PERCENT_VALUE`, `PRINCIPAL_MODE`, `YMD_FLAG`, `YEAR_BASE_DAY`, `MONTH_BASE_DAY`) VALUES ('1', '2016-05-22 23:04:09', '2016-05-22 22:01:53', '222223', '3', ' ', '1', '-1', '3', '1', '0', '3', '2000', '0', '1', '365', '30');


DROP TABLE IF EXISTS M_PRODUCT_RULE;
CREATE TABLE M_PRODUCT_RULE (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  PRODUCT_ID BIGINT NOT NULL COMMENT '基础产品ID',
  PRODUCT_NAME VARCHAR NOT NULL DEFAULT '' COMMENT '基础产品名称',
  DESCRIPTION VARCHAR NOT NULL DEFAULT '' COMMENT '描述',
  PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
  PRODUCT_RULE_STATUS INT NOT NULL COMMENT '产品规则状态',
  ACCOUNT_TYPE INT NOT NULL COMMENT ' 账户类型',
  CYCLE_TYPE INT NOT NULL COMMENT '分期类型',
  CYCLE_COUNT INT NOT NULL COMMENT '分期期数',
  REPAY_MODE_ID BIGINT NOT NULL COMMENT '还款方式ID，关联息费模块还款方式表',
  MINI_REPAY_TYPE INT NOT NULL COMMENT '最小还款额方式',
  INTEREST_START_TYPE INT NOT NULL COMMENT '起息日规则',
  CREDIT_LIMIT_RULE_ID BIGINT NOT NULL COMMENT '信用额度规则模板ID',
  PERIOD_GRACE INT NOT NULL COMMENT '宽限期，从还款日开始计算',
  MINI_REPAY_RATE INT NOT NULL COMMENT '最小还款比例，分母为10000',
  MINI_REPAY_AMOUNT INT NOT NULL COMMENT '最小还款金额',
  WRITE_OFF_RULE_ID BIGINT NOT NULL COMMENT '冲销顺序规则ID',
  BILL_DAY_RULE INT NOT NULL COMMENT '账单日规则',
  BILL_DAY INT NOT NULL COMMENT '账单日',
  REPAY_DAY_RULE INT NOT NULL COMMENT '还款日规则',
  CONSUME_INSTALLMENT_RULE INT NOT NULL COMMENT '消费分期规则',
  BILL_INSTALLMENT_RULE INT NOT NULL COMMENT '账单分期规则    ',
  REPAY_DAY INT NOT NULL COMMENT '还款日',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY_ID BIGINT NOT NULL COMMENT '修改人ID',
  START_DATE TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '有效期开始时间',
  END_DATE TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '有效期结束时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '创建时间',
  CREATE_ID BIGINT NOT NULL COMMENT '创建人ID',
  VERIFIED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '审核时间',
  INTEREST_START_DAY int NOT NULL COMMENT '起息日',
  VERIFY_ID BIGINT NOT NULL COMMENT '审核人ID'
);
CREATE PRIMARY KEY ON M_PRODUCT_RULE(ID);



DROP TABLE IF EXISTS M_REPAYMENT_METHOD;
CREATE TABLE M_REPAYMENT_METHOD (
  STATUS INT NOT NULL COMMENT '状态',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  REPAYMENT_METHOD_ID BIGINT NOT NULL COMMENT '还款方式ID',
  REPAYMENT_METHOD_NAME VARCHAR(150) NOT NULL COMMENT '还款方式名称',
  PRINCIPAL_TREATMENT INT NOT NULL COMMENT '本金处理方式',
  TEMPLATE_COUNT INT NOT NULL COMMENT '模板期数',
  FREE_COUNT INT NOT NULL COMMENT '空档期'
);
CREATE PRIMARY KEY ON M_REPAYMENT_METHOD(ID);
CREATE INDEX IDX_REPAYMENT_METHOD ON M_REPAYMENT_METHOD(REPAYMENT_METHOD_ID);



DROP TABLE IF EXISTS T_ACCG_REQ_LIST;
CREATE TABLE T_ACCG_REQ_LIST (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增字段',
  STATE INT NOT NULL COMMENT '入账状态',
  REQ_TYPE INT NOT NULL COMMENT '请求类型',
  TRANSACTION_ID BIGINT NOT NULL COMMENT '交易流水',
  ACCOUNTING_NO BIGINT NOT NULL COMMENT '入账序号',
  TRANS_MSG VARCHAR(128) DEFAULT NULL COMMENT '交易说明',
  ACCOUNT_TYPE INT NOT NULL COMMENT '账务类型',
  TRANSACTION_CODE VARCHAR(32) NOT NULL COMMENT '交易码',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户号',
  ACCOUNT_ID BIGINT DEFAULT NULL COMMENT '账号ID',
  LOAN_ID BIGINT NOT NULL COMMENT '借据号',
  LOAN_SCHEDULE_NO INT NOT NULL COMMENT '借据分期序号',
  BILL_ID BIGINT NOT NULL COMMENT '信用账单号',
  BILL_NO INT NOT NULL COMMENT '信用账单分期序号',
  CONSUME_ID BIGINT NOT NULL COMMENT '信用消费号',
  CONSUME_NO INT NOT NULL COMMENT '信用消费分期序号',
  OFF_IND INT NOT NULL COMMENT '还清指示',
  PRODUCT_ID BIGINT NOT NULL COMMENT '产品id',
  PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
  INSTITUTION BIGINT NOT NULL COMMENT '资金机构',
  CAPITAL_CHANNEL INT DEFAULT NULL COMMENT '支付渠道',
  SECURITY_IND INT NOT NULL COMMENT '证券化状态',
  PRINCIPAL_ALL BIGINT NOT NULL COMMENT '本金总额',
  PRINCIPAL BIGINT NOT NULL COMMENT '本金金额',
  PRINCIPAL_REDUCE BIGINT NOT NULL COMMENT '本金减免',
  PRINCIPAL_ADJUST BIGINT NOT NULL COMMENT '本金调整',
  INTEREST_ALL BIGINT NOT NULL COMMENT '利息总金额',
  INTEREST BIGINT NOT NULL COMMENT '利息金额',
  INTEREST_REDUCE BIGINT NOT NULL COMMENT '利息减免',
  INTEREST_ADJUST BIGINT NOT NULL COMMENT '利息调整',
  CHARGES BIGINT NOT NULL COMMENT '费用金额',
  CHARGES_REDUCE BIGINT NOT NULL COMMENT '费用减免',
  CHARGES_ADJUST BIGINT NOT NULL COMMENT '费用调整',
  PENALTY BIGINT NOT NULL COMMENT '罚息金额',
  PENALTY_REDUCE BIGINT NOT NULL COMMENT '罚息减免',
  PENALTY_ADJUST BIGINT NOT NULL COMMENT '罚息调整',
  OVERDUE BIGINT NOT NULL COMMENT '滞纳金金额',
  OVERDUE_REDUCE BIGINT NOT NULL COMMENT '滞纳金减免',
  OVERDUE_ADJUST BIGINT NOT NULL COMMENT '滞纳金调整',
  VIOLATE BIGINT NOT NULL COMMENT '违约金金额',
  VIOLATE_REDUCE BIGINT NOT NULL COMMENT '违约金减免',
  VIOLATE_ADJUST BIGINT NOT NULL COMMENT '违约金调整',
  DISCOUNT_ALL BIGINT NOT NULL COMMENT '贴息总额',
  DISCOUNT BIGINT NOT NULL COMMENT '贴息金额',
  DISCOUNT_REDUCE BIGINT NOT NULL COMMENT '贴息减免',
  DISCOUNT_ADJUST BIGINT NOT NULL COMMENT '贴息调整',
  MANAGEMENT_ALL BIGINT NOT NULL COMMENT '账户管理费总额',
  MANAGEMENT BIGINT NOT NULL COMMENT '账户管理费',
  MANAGEMENT_REDUCE BIGINT NOT NULL COMMENT '账户管理费减免',
  MANAGEMENT_ADJUST BIGINT NOT NULL COMMENT '账户管理费调整',
  SERVICE BIGINT NOT NULL COMMENT '服务费',
  SERVICE_REDUCE BIGINT NOT NULL COMMENT '服务费减免',
  SERVICE_ADJUST BIGINT NOT NULL COMMENT '服务费调整',
  FEE BIGINT NOT NULL COMMENT '预留费用',
  FEE_REDUCE BIGINT NOT NULL COMMENT '预留费用减免',
  FEE_ADJUST BIGINT NOT NULL COMMENT '预留费用调整',
  DUES BIGINT NOT NULL COMMENT '会费预留',
  DUES_REDUCE BIGINT NOT NULL COMMENT '会费减免预留',
  DUES_ADJUST BIGINT NOT NULL COMMENT '会费调整预留',
  EXPENSE BIGINT NOT NULL COMMENT '运输费用预留',
  EXPENSE_REDUCE BIGINT NOT NULL COMMENT '运输费用减免预留',
  EXPENSE_ADJUST BIGINT NOT NULL COMMENT '运输费用调整预留',
  COST BIGINT NOT NULL COMMENT '成本费用预留',
  COST_REDUCE BIGINT NOT NULL COMMENT '成本费用减免预留',
  COST_ADJUST BIGINT NOT NULL COMMENT '成本费用调整预留',
  OVER_FLOW BIGINT NOT NULL COMMENT '溢缴款',
  ACCOUNT_DATE DATE NOT NULL COMMENT '请求账务日期',
  LIST_ID BIGINT DEFAULT NULL COMMENT '账务请求ID',
  LIST_DATE DATE DEFAULT NULL COMMENT '账务会计日期',
  START_DATE DATE DEFAULT NULL COMMENT '分期计提开始日期',
  DUE_DATE DATE DEFAULT NULL COMMENT '分期计提结束日期',
  DELETE_FLAG INT NOT NULL COMMENT '记录物理状态',
  VERSION INT NOT NULL COMMENT '乐观锁版本',
  APP_TYPE INT NOT NULL COMMENT '金融核心场景',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '创建时间'
);

 DROP TABLE IF EXISTS T_ACCG_REQ_LIST_0_20160719;
CREATE TABLE T_ACCG_REQ_LIST_0_20160719 (
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增字段',
STATE INT NOT NULL COMMENT '入账状态',
TRANSACTION_ID BIGINT NOT NULL COMMENT '交易流水',
ACCOUNTING_NO BIGINT NOT NULL COMMENT '入账序号',
REQ_TYPE INT NOT NULL COMMENT '请求类型',
TRANS_MSG VARCHAR(128) COMMENT '交易说明',
ACCOUNT_TYPE INT NOT NULL COMMENT '账务类型',
TRANSACTION_CODE VARCHAR(32) NOT NULL COMMENT '交易码',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户号',
ACCOUNT_ID BIGINT COMMENT '账号ID',
LOAN_ID BIGINT NOT NULL COMMENT '借据号',
LOAN_SCHEDULE_NO INT NOT NULL COMMENT '借据分期序号',
BILL_ID BIGINT NOT NULL COMMENT '信用账单号',
BILL_NO INT NOT NULL COMMENT '信用账单分期序号',
CONSUME_ID BIGINT NOT NULL COMMENT '信用消费号',
CONSUME_NO INT NOT NULL COMMENT '信用消费分期序号',
OFF_IND INT NOT NULL COMMENT '还清指示',
PRODUCT_ID BIGINT NOT NULL COMMENT '产品id',
PRODUCT_NO BIGINT NOT NULL COMMENT '产品序号',
INSTITUTION BIGINT NOT NULL COMMENT '资金机构',
CAPITAL_CHANNEL INT COMMENT '支付渠道',
SECURITY_IND INT NOT NULL COMMENT '证券化状态',
PRINCIPAL_ALL BIGINT NOT NULL COMMENT '本金总额',
PRINCIPAL BIGINT NOT NULL COMMENT '本金金额',
PRINCIPAL_REDUCE BIGINT NOT NULL COMMENT '本金减免',
PRINCIPAL_ADJUST BIGINT NOT NULL COMMENT '本金调整',
INTEREST_ALL BIGINT NOT NULL COMMENT '利息总金额',
INTEREST BIGINT NOT NULL COMMENT '利息金额',
INTEREST_REDUCE BIGINT NOT NULL COMMENT '利息减免',
INTEREST_ADJUST BIGINT NOT NULL COMMENT '利息调整',
CHARGES BIGINT NOT NULL COMMENT '费用金额',
CHARGES_REDUCE BIGINT NOT NULL COMMENT '费用减免',
CHARGES_ADJUST BIGINT NOT NULL COMMENT '费用调整',
PENALTY BIGINT NOT NULL COMMENT '罚息金额',
PENALTY_REDUCE BIGINT NOT NULL COMMENT '罚息减免',
PENALTY_ADJUST BIGINT NOT NULL COMMENT '罚息调整',
OVERDUE BIGINT NOT NULL COMMENT '滞纳金金额',
OVERDUE_REDUCE BIGINT NOT NULL COMMENT '滞纳金减免',
OVERDUE_ADJUST BIGINT NOT NULL COMMENT '滞纳金调整',
VIOLATE BIGINT NOT NULL COMMENT '违约金金额',
VIOLATE_REDUCE BIGINT NOT NULL COMMENT '违约金减免',
VIOLATE_ADJUST BIGINT NOT NULL COMMENT '违约金调整',
DISCOUNT_ALL BIGINT NOT NULL COMMENT '贴息总额',
DISCOUNT BIGINT NOT NULL COMMENT '贴息金额',
DISCOUNT_REDUCE BIGINT NOT NULL COMMENT '贴息减免',
DISCOUNT_ADJUST BIGINT NOT NULL COMMENT '贴息调整',
MANAGEMENT_ALL BIGINT NOT NULL COMMENT '账户管理费总额',
MANAGEMENT BIGINT NOT NULL COMMENT '账户管理费',
MANAGEMENT_REDUCE BIGINT NOT NULL COMMENT '账户管理费减免',
MANAGEMENT_ADJUST BIGINT NOT NULL COMMENT '账户管理费调整',
SERVICE BIGINT NOT NULL COMMENT '服务费',
SERVICE_REDUCE BIGINT NOT NULL COMMENT '服务费减免',
SERVICE_ADJUST BIGINT NOT NULL COMMENT '服务费调整',
FEE BIGINT NOT NULL COMMENT '预留费用',
FEE_REDUCE BIGINT NOT NULL COMMENT '预留费用减免',
FEE_ADJUST BIGINT NOT NULL COMMENT '预留费用调整',
DUES BIGINT NOT NULL COMMENT '会费预留',
DUES_REDUCE BIGINT NOT NULL COMMENT '会费减免预留',
DUES_ADJUST BIGINT NOT NULL COMMENT '会费调整预留',
EXPENSE BIGINT NOT NULL COMMENT '运输费用预留',
EXPENSE_REDUCE BIGINT NOT NULL COMMENT '运输费用减免预留',
EXPENSE_ADJUST BIGINT NOT NULL COMMENT '运输费用调整预留',
COST BIGINT NOT NULL COMMENT '成本费用预留',
COST_REDUCE BIGINT NOT NULL COMMENT '成本费用减免预留',
COST_ADJUST BIGINT NOT NULL COMMENT '成本费用调整预留',
OVER_FLOW BIGINT NOT NULL COMMENT '溢缴款',
ACCOUNT_DATE DATE NOT NULL COMMENT '请求账务日期',
LIST_ID BIGINT COMMENT '账务请求ID',
LIST_DATE DATE COMMENT '账务会计日期',
START_DATE DATE COMMENT '分期计提开始日期',
DUE_DATE DATE COMMENT '分期计提结束日期',
ORIGINAL_DATE DATE COMMENT '冲正，撤销原始交易日期',
DELETE_FLAG INT NOT NULL COMMENT '记录物理状态',
VERSION INT NOT NULL COMMENT '乐观锁版本',
APP_TYPE INT NOT NULL COMMENT '金融核心场景',
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',

PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS T_CONSUME;
CREATE TABLE T_CONSUME
(
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT COMMENT '账号ID',
  PRODUCT_ID BIGINT COMMENT '产品ID',
  PRODUCT_NO BIGINT COMMENT '产品序号',
  TRANSACTION_ID BIGINT NOT NULL COMMENT '交易ID',
  CONSUME_ID BIGINT NOT NULL COMMENT '消费明细ID',
  BILL_ID BIGINT COMMENT '对应账单ID',
  TRANSACTION_DATE DATE NOT NULL COMMENT '交易发起日期',
  TRANSACTION_CONFIRMED_DATE DATE COMMENT '交易确认日期',
  TRANSACTION_CANCELLED_DATE DATE COMMENT '交易取消日期',
  BILL_DATE DATE NOT NULL COMMENT '账单日期',
  REPAY_DATE DATE NOT NULL COMMENT '还款日期',
  CONSUME_AMOUNT BIGINT NOT NULL COMMENT '交易总额',
  CONSUME_STATUS INT NOT NULL COMMENT '消费状态',
  REPAID_AMOUNT BIGINT COMMENT '已还金额',
  BILL_STATUS INT NOT NULL COMMENT '账单状态',
  INSTALLMENT_STATUS INT NOT NULL COMMENT '分期状态',
  INSTALLMENT_BILL_ID BIGINT COMMENT '转分期的分期账单id',
  NOTES VARCHAR(32) COMMENT '摘要说明',
  PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS T_CREDIT_INSTALLMENT;
CREATE TABLE T_CREDIT_INSTALLMENT
(
  MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  INSTALLMENT_ID BIGINT COMMENT '全局唯一ID',
  INSTALLMENT_TYPE INT COMMENT '分期类型',
  BILL_ID BIGINT COMMENT '账单ID',
  CONSUME_ID BIGINT COMMENT '消费ID',
  CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
  ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
  PRODUCT_ID BIGINT COMMENT '产品ID',
  PRODUCT_NO BIGINT COMMENT '产品序号',
  INSTALLMENT_COUNT INT COMMENT '总分期数',
  INSTALLMENT_NO INT COMMENT '分期序号',
  ACCOUNT_DATE DATE NOT NULL COMMENT '帐务日期',
  BILL_DATE DATE NOT NULL COMMENT '账单日',
  DUE_DATE DATE NOT NULL COMMENT '到期还款日',
  PRINCIPAL BIGINT NOT NULL COMMENT '本金总金额',
  PRINCIPAL_REPAID BIGINT NOT NULL COMMENT '本金已还金额',
  PRINCIPAL_UNPAID BIGINT NOT NULL COMMENT '本金未还金额',
  CHARGES BIGINT NOT NULL COMMENT '费用总额',
  CHARGES_REPAID BIGINT NOT NULL COMMENT '费用已还金额',
  CHARGES_UNPAID BIGINT NOT NULL COMMENT '费用未还金额',
  PENALTY BIGINT NOT NULL COMMENT '罚息总额',
  PENALTY_REPAID BIGINT NOT NULL COMMENT '罚息已还金额',
  PENALTY_UNPAID BIGINT NOT NULL COMMENT '罚息未还金额',
  OVERDUE BIGINT NOT NULL COMMENT '逾期费总额',
  OVERDUE_REPAID BIGINT NOT NULL COMMENT '逾期费已还金额',
  OVERDUE_UNPAID BIGINT NOT NULL COMMENT '逾期费未还金额',
  VIOLATE BIGINT COMMENT '违约金总额',
  VIOLATE_REPAID BIGINT NOT NULL COMMENT '违约金已还金额',
  VIOLATE_UNPAID BIGINT COMMENT '违约金未还金额',
  REPAID_STATUS INT NOT NULL COMMENT '还款状态',
  INSTALLMENT_STATUS INT NOT NULL COMMENT '信用支付分期状态',
  BILL_STATUS INT NOT NULL COMMENT '账单状态',
  PRIMARY KEY(ID)
);
CREATE PRIMARY KEY ON T_ACCG_REQ_LIST(ID);
CREATE UNIQUE INDEX IDX_REQ ON T_ACCG_REQ_LIST(REQ_TYPE,TRANSACTION_ID,ACCOUNTING_NO);

DROP TABLE IF EXISTS M_MONEY_META;
CREATE TABLE M_MONEY_META (
  STATUS int NOT NULL COMMENT '状态',
  MODIFIED timestamp NOT NULL  COMMENT '更新时间',
  CREATED timestamp NOT NULL  COMMENT '创建时间',
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  META_ID bigint NOT NULL COMMENT '元数据ID',
  TRAN_TYPE int NOT NULL COMMENT '交易类型',
  META_NAME varchar NOT NULL COMMENT '元数据名称',
  META_KEY int NOT NULL COMMENT '元数据KEY',
  META_VALUE bigint NOT NULL COMMENT '元数据VALUE',
  PRIMARY KEY (ID),
  KEY IDX_META (META_ID)
);

DROP TABLE IF EXISTS M_WRITE_OFF;
CREATE TABLE M_WRITE_OFF (
  MODIFIED timestamp NOT NULL COMMENT '更新时间',
  CREATED timestamp NOT NULL  COMMENT '创建时间',
  ID bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  WRITE_OFF_ID int(11) DEFAULT NULL COMMENT '冲销顺序ID',
  WRITE_OFF_ORDER varchar NOT NULL COMMENT '冲销顺序',
  PRIMARY KEY (ID),
  UNIQUE KEY IDX_WRITE_OFF_ID (WRITE_OFF_ID)
);

DROP TABLE IF EXISTS M_WORKER_NODE;
CREATE TABLE M_WORKER_NODE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  HOST_NAME VARCHAR(64) NOT NULL,
  PORT VARCHAR(64) NOT NULL,
  TYPE INT NOT NULL,
  LAUNCH_DATE DATE NOT NULL,
  MODIFIED TIMESTAMP,
  CREATED TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY U_INDEX_HOST_PORT (HOST_NAME,PORT)
);



 DROP TABLE IF EXISTS T_CREDIT_ACCOUNT_0_0;
CREATE TABLE T_CREDIT_ACCOUNT_0_0
(
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
ACCOUNT_AGING INT NOT NULL COMMENT '账号账龄',
ACCOUNT_STATUS INT NOT NULL COMMENT '账号状态',
STATUS_END_DATE DATE NOT NULL COMMENT '状态截止日期',
DEBIT_STATUS INT NOT NULL COMMENT '借贷状态',
OVERFLOW BIGINT NOT NULL COMMENT '溢缴款',
FINANCING_SOURCE BIGINT NOT NULL COMMENT '资金机构',
TEMPLATE_ID INT NOT NULL COMMENT '配置模版ID',
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
PRIMARY KEY(ID),
UNIQUE IDX_ACCOUNT(ACCOUNT_ID)
);

DROP TABLE IF EXISTS T_CREDIT_ACCOUNT_FACTOR_0_0;
CREATE TABLE T_CREDIT_ACCOUNT_FACTOR_0_0
(
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
FACTOR_TYPE INT NOT NULL COMMENT '类型',
FACTOR_NAME VARCHAR(32) NOT NULL COMMENT '名称',
FACTOR_VALUE BIGINT NOT NULL COMMENT '值',
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
PRIMARY KEY(ID),
 
);

DROP TABLE IF EXISTS M_CREDIT_ACCOUNT_CONFIG;
CREATE TABLE M_CREDIT_ACCOUNT_CONFIG
(
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
TEMPLATE_ID INT NOT NULL COMMENT '模版ID',
FACTOR_TYPE INT NOT NULL COMMENT '类型',
FACTOR_NAME VARCHAR(32) NOT NULL COMMENT '名称',
FACTOR_VALUE BIGINT NOT NULL COMMENT '值',
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
PRIMARY KEY(ID),
);

DROP TABLE IF EXISTS T_WRITE_OFF_RECORD_0_0;
CREATE TABLE T_WRITE_OFF_RECORD_0_0
(
MODIFIED TIMESTAMP NOT NULL COMMENT '记录修改时间',
CREATED TIMESTAMP NOT NULL COMMENT '记录创建时间',
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
ACCOUNT_TYPE INT NOT NULL COMMENT '冲销的账户类型',
BILL_ID BIGINT NOT NULL COMMENT '账单ID',
BILL_DATE DATE NOT NULL COMMENT '账单日',
DESTINATION INT NOT NULL COMMENT '冲销消费或分期',
DESTINATION_ID BIGINT NOT NULL COMMENT '冲销的消费或分期的 ID',
WRITE_OFF_DATE DATE NOT NULL COMMENT '冲销时间',
WRITE_OFF_MONEY BIGINT NOT NULL COMMENT '冲销金额',
PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS H_CONSUME_OPERATION_0_0;
CREATE TABLE H_CONSUME_OPERATION_0_0
(
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
TRANSACTION_ID BIGINT NOT NULL COMMENT '交易流水ID',
CONSUME_ID BIGINT NOT NULL COMMENT '消费明细ID',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
PRODUCT_ID BIGINT NOT NULL COMMENT '产品ID',
ACCOUNT_DATE DATE NOT NULL COMMENT '账务日期',
ORIGINAL_PRODUCT_NO BIGINT NOT NULL COMMENT '变更前产品序号',
NEW_PRODUCT_NO BIGINT NOT NULL COMMENT '变更后产品序号',
ORIGINAL_CONSUME_STATUS INT NOT NULL COMMENT '变更前消费状态',
NEW_CONSUME_STATUS INT NOT NULL COMMENT '变更后消费状态',
ORIGINAL_REPAID_AMOUNT BIGINT NOT NULL COMMENT '变更前已还金额',
NEW_REPAID_AMOUNT BIGINT NOT NULL COMMENT '变更后已还金额',
ORIGINAL_OVER_PAID BIGINT NOT NULL COMMENT '变更前溢缴款',
NEW_OVER_PAID BIGINT NOT NULL COMMENT '变更后溢缴款',
ORIGINAL_INSTALLMENT_STATUS INT NOT NULL COMMENT '变更前转分期状态',
NEW_INSTALLMENT_STATUS INT NOT NULL COMMENT '变更后转分期状态',
PRIMARY KEY(ID),
INDEX IDX_CUSTOMER(CUSTOMER_ID),
INDEX IDX_ACCOUNT(ACCOUNT_ID),
INDEX IDX_CONSUME(CONSUME_ID)
);

DROP TABLE IF EXISTS H_TRANSACTION_0_0;
CREATE TABLE H_TRANSACTION_0_0
(
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
REQUEST_ID VARCHAR(32) NOT NULL COMMENT '前置请求流水号',
SUB_REQUEST_ID BIGINT NOT NULL COMMENT '子前置请求流水号',
TRANSACTION_ID BIGINT NOT NULL COMMENT '核心流水ID',
RELATED_TRANSACTION_ID BIGINT COMMENT '关联流水ID',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
ACCOUNT_ID BIGINT NOT NULL COMMENT '账号ID',
PRODUCT_ID BIGINT COMMENT '产品ID',
CONTRACT_ID BIGINT COMMENT '签约ID',
PAYMENT_CHANNEL BIGINT COMMENT '支付渠道',
FINANCING_SOURCE BIGINT COMMENT '资金机构',
TRANSACTION_AMOUNT BIGINT NOT NULL COMMENT '交易金额',
BUSINESS_TYPE INT NOT NULL COMMENT '业务类型',
TRANSACTION_DATE DATE NOT NULL COMMENT '交易发起日期',
TRANSACTION_CODE VARCHAR(32) NOT NULL COMMENT '交易码',
LOAN_ID BIGINT COMMENT '借据号',
CONSUME_ID BIGINT COMMENT '消费记录号',
BILL_ID BIGINT COMMENT '账单号',
DEBIT_ID BIGINT COMMENT '余额交易ID',
PRIMARY KEY(ID)
 
);
DROP TABLE IF EXISTS H_LOAN_OPERATION_VALUE_0_0;
CREATE TABLE H_LOAN_OPERATION_VALUE_0_0
(
MODIFIED TIMESTAMP NOT NULL COMMENT '更新时间',
CREATED TIMESTAMP NOT NULL COMMENT '创建时间',
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
TRANSACTION_ID BIGINT NOT NULL COMMENT '借据ID或分期交易流水ID',
SOURCE_TYPE INT NOT NULL COMMENT '借据或分期',
CUSTOMER_ID BIGINT NOT NULL COMMENT '客户ID',
OPERATION_TYPE INT NOT NULL COMMENT '操作类型',
SCHEDULE_NO INT NOT NULL COMMENT '借据期序号',
INSTALLMENT_MADE_NO INT NOT NULL COMMENT '借据被分期序号',
BEFORE_VALUE_INT BIGINT NOT NULL COMMENT '变更前INT值',
AFTER_VALUE_INT BIGINT NOT NULL COMMENT '变更后INT值',
BEFORE_VALUE_STRING VARCHAR(32) COMMENT '变更前字符串值',
AFTER_VALUE_STRING VARCHAR(32) COMMENT '变更后字符串值',
PRIMARY KEY(ID)
)