CREATE TABLE M_PRICING_METHOD
(
  STATUS INT NOT NULL COMMENT '状态',
  MODIFIED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  CREATED TIMESTAMP NOT NULL DEFAULT '2000-01-01 00:00:01' COMMENT '创建时间',
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  PRICING_METHOD_ID BIGINT NOT NULL COMMENT '定价方式ID',
  PRICING_METHOD_NAME CHARACTER VARYING(150) NOT NULL COMMENT '定价方式名称',
  PRICING_TYPE INT NOT NULL COMMENT '定价类型',
  PRICING_MODE INT NOT NULL COMMENT '定价计算规则',
  FIXED_AMOUNT BIGINT NOT NULL COMMENT '固定收取金额',
  MIN_AMOUNT BIGINT NOT NULL COMMENT '最小收取金额',
  PERCENT_VALUE INT NOT NULL COMMENT '利率',
  PRINCIPAL_MODE INT NOT NULL COMMENT '本金处理方式',
  YMD_FLAG INT NOT NULL COMMENT '年月日标志',
  YEAR_BASE_DAY INT NOT NULL COMMENT '年基准天数',
  MONTH_BASE_DAY INT NOT NULL COMMENT '月基准天数',
  PRIMARY KEY(ID),
  INDEX IDX_PRICE(PRICING_METHOD_ID)
) engine=innodb DEFAULT CHARSET=utf8 COMMENT='息费定价方式表';

insert into M_PRICING_METHOD (CREATED, STATUS, PRICING_METHOD_ID, PRICING_METHOD_NAME, PRICING_TYPE, PRICING_MODE, FIXED_AMOUNT, PERCENT_VALUE, PRINCIPAL_MODE, YMD_FLAG, YEAR_BASE_DAY, MONTH_BASE_DAY) values(now(), 1, 3, '', 3, 1, 0, 500, 1, 0, 365, 30);
insert into M_PRICING_METHOD (CREATED, STATUS, PRICING_METHOD_ID, PRICING_METHOD_NAME, PRICING_TYPE, PRICING_MODE, FIXED_AMOUNT, PERCENT_VALUE, PRINCIPAL_MODE, YMD_FLAG, YEAR_BASE_DAY, MONTH_BASE_DAY) values(now(), 1, 4, '', 4, 1, 0, 800, 1, 0, 365, 30);
